Error: Netwrok request failed
Implemented ApolloClient to consume the local graphql api, but getting Error: Netwrok request failed
I believe the request needs to be served over https